async function main() {
  console.error(`No action`);
}

main().catch(err => { console.error(err); process.exit(1); });